version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: x64
nuget:
  project_feed: true
before_build:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.dd).$env:appveyor_build_number"
build:
  project: C:\projects\blockthespot\src\BlockTheSpot.vcxproj
  verbosity: minimal
after_build:
- pwsh: Get-ChildItem -Path C:\projects\blockthespot\src\x64\Release\*.dll, C:\projects\blockthespot\*.ini | Compress-Archive -DestinationPath C:\projects\blockthespot\chrome_elf.zip
test: off
artifacts:
- path: chrome_elf.zip
deploy:
- provider: GitHub
  description: appveyor automatic release
  auth_token:
    secure: fAOGXS/tEQqVw+u6JcQ3E/YzSrECseAsgm8E0NEqAozsrfxjSJ/u+G/0sVOuDeia
  artifact: chrome_elf.zip
  draft: false
  force_update: false